### ISSUE TITLE
Retrying payment

### ISSUE THREAD

**Issue by jumika** [schmittjoh/JMSPaymentPaypalBundle#81]
How should i retry a payment after the user left the express checkout screen, or clicked cancel?
I've seen other issues mentioning reason code 10419 which i'm getting.

I guess i should make a new payment since the old one's status set to failed after calling approveAndDeposit on the payment.plugin_controller. But i have no idea how to do that to get a valid payment.

I'm using the example code fond in the usage documentation and i'm ending up in the
`Result::STATUS_SUCCESS !== $result->getStatus()` block getting the exception 

> Transaction not successfull! Reason: 10419

**Comment by regularjack** [comment]
`10419` is probably because you're not setting the `useraction=commit` option, see [the documentation](http://jmspaymentpaypalbundle.readthedocs.io/en/stable/usage.html#useraction) for more information.

As for what to do when the user clicks cancel, you are correct in assuming you would create a new payment. When the user clicks cancel, they are redirected to the URL you have passed to the  `cancel_url` option. Did you check the [Accepting payments guide](http://jmspaymentcorebundle.readthedocs.io/en/latest/guides/accepting_payments.html#depositing-money) in JMSPaymentCore's docs?

**Comment by jumika** [comment]
`useraction` is set in config.yml.
I'm using the same code shown on that page. Of course with the "Performing the payment offsite" addition.

**Comment by regularjack** [comment]
I haven't been able to reproduce the `10419` code. Would it be possible for you to create a minimal Symfony project that reproduces the issue and put it up on GitHub?
